version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: portfolio-web-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
      - db
      - introduce-nginx
    networks:
      - webnet

  introduce-nginx:
    image: nginx:latest
    container_name: introduce-web-server
    volumes:
      - ./volumes/previnfo:/usr/share/nginx/html
      - ./introduce-nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet
    environment:
      VIRTUAL_HOST: introduce.effozen.com

  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: nodejs_server
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    networks:
      - webnet

  db:
    image: mysql:8.0
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webnet

networks:
  webnet:

