version: '3'

services:
  portfolio-web-server:
    image: nginx:latest
    container_name: portfolio-web-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
      - db
    networks:
      - webnet

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_server
    ports:
      - "50000:50000"
      - "8083:8080"
    volumes:
      - ./volumes/jenkins_home:/var/jenkins_home
      - ./volumes/web:/web/
    networks:
      - webnet

  db:
    image: mysql:latest
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webnet

  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: nodejs_server
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    networks:
      - webnet

networks:
  webnet:

